const ProductsMessages = {
    tr: {
        boyutlar: "Boyutlar",
        uzunluk: "Uzunluk",
        genislik: "Genişlik",
        yukseklik: "Yükseklik",
        agirlik: "Ağırlık",
        enerji_ozellikleri: "Enerji Özellikleri",
        yakit_tipi: "YAKIT TİPİ",
        elektrik: "Elektrik",
        motorin: "Motorin",
        lpg: "Lpg",
        dogal_gaz: "Doğal Gaz",
        minimum: "Minimum",
        maximum: "Maximum",
        ortalama: "Ortalama",
        viewModel: "3D Modeli Görüntüle",
        capacity: "Ürün Kapasiteleri",
        electric_component: "Elektrik Bileşenleri",
        urun_kapasitesi: "ÜRÜN KAPASİTESİ",
        kapasite: "KAPASİTE",
        kg_saat: "KG/SAAT",
        mm: "mm",
        lt_h: "lt/h",
        kw: "kW",
        nm3_h: "Nm3/h",
        kg_h: "KG/SAAT",
        kg: "kg",
        resistance: "Rezistans",

        fistik: "Fıstık",
        kabuklu_fistik: "Kabuklu Fıstık",
        tuzlu_fistik: "Tuzlu Fıstık",
        antep_fistigi: "Antep Fıstığı",
        soslu_fistik: "Soslu Fıstık",
        kaplamali_fistik: "Kaplamalı Fıstık",
        tofy_fistik: "Tofy Fıstık",
        amigo_fistik: "Amigo Fıstık",
        leblebi: "Leblebi",
        beyaz_leblebi: "Beyaz Leblebi",
        sari_leblebi: "Sarı Leblebi",
        citir_leblebi: "Çıtır Leblebi",
        kaplamali_leblebi: "Kaplamalı Leblebi",
        tofy_leblebi: "Tofy Leblebi",
        soslu_leblebi: "Soslu Leblebi",
        ham_leblebi: "Ham Leblebi",
        tuzlu_leblebi: "Tuzlu Leblebi",
        leblebi_sekeri: "Leblebi Şekeri",
        ay_cekirdegi: "Ay Çekirdeği",
        kabak_cekirdegi: "Kabak Çekirdeği",
        badem: "Badem",
        kabuklu_badem: "Kabuklu Badem",
        badem_sekeri: "Badem Şekeri",
        kahve: "Kahve",
        cips: "Cips",
        misir: "Mısır",
        kaju: "Kaju",
        findik: "Fındık",
        ceviz: "Ceviz",
        kabuklu_findik: "Kabuklu Fındık",

        benzerUrunler: "Benzer Ürünler",
        teklifAl: "Teklif Al",
        incele: "İncele",
        
        name: "Ad",
        email: "E-Posta",
        phone: "Telefon",
        address: "Adres",
        message: "Mesaj",
        message_desc: "Mesajınızı Buraya Yazın...",
        submit: "Gönder",
        sending: "Gönderiliyor",
        success_message: "Mesajınız ulaştı teşekkür ederiz.",
        success: "Başarılı",
        error: "Hata",
    },
    en: {
        boyutlar: "Dimensions",
        uzunluk: "Length",
        genislik: "Width",
        yukseklik: "Height",
        agirlik: "Weight",
        enerji_ozellikleri: "Energy Specifications",
        yakit_tipi: "FUEL TYPE",
        elektrik: "Electric",
        motorin: "Diesel",
        lpg: "LPG",
        dogal_gaz: "Natural Gas",
        minimum: "Minimum",
        maximum: "Maximum",
        ortalama: "Average",
        viewModel: "View 3D Model",
        capacity: "Product Capacities",
        electric_component: "Electric Components",
        urun_kapasitesi: "PRODUCT CAPACITY",
        kapasite: "CAPACITY",
        kg_saat: "KG/H",
        mm: "mm",
        lt_h: "lt/h",
        kw: "kW",
        nm3_h: "Nm3/h",
        kg_h: "kg/h",
        kg: "kg",
        resistance: "Resistance",

        fistik: "Peanut",
        kabuklu_fistik: "Shelled Peanuts",
        tuzlu_fistik: "Salted Peanuts",
        antep_fistigi: "Pistachios",
        soslu_fistik: "Peanut with Sauce",
        kaplamali_fistik: "Coated Peanuts",
        tofy_fistik: "Tofy Peanut",
        amigo_fistik: "Amigo Peanut",
        leblebi: "Chickpea",
        beyaz_leblebi: "White Chickpeas",
        sari_leblebi: "Yellow Chickpeas",
        citir_leblebi: "Crispy Chickpeas",
        kaplamali_leblebi: "Coated Chickpeas",
        tofy_leblebi: "Tofy Chickpeas",
        soslu_leblebi: "Chickpeas with Sauce",
        ham_leblebi: "Raw Chickpeas",
        tuzlu_leblebi: "Salted Chickpeas",
        leblebi_sekeri: "Chickpeas Candys",
        ay_cekirdegi: "Sunflower seeds",
        kabak_cekirdegi: "Pumpkin seeds",
        badem: "Almond",
        kabuklu_badem: "Shelled Almonds",
        badem_sekeri: "Almond candy",
        kahve: "Coffee",
        cips: "Chips",
        misir: "Corn",
        kaju: "Cashew",
        findik: "Hazelnut",
        ceviz: "Walnut",
        kabuklu_findik: "Shelled Hazelnut",

        benzerUrunler: "Similar Products",
        teklifAl: "Get A Quote",
        incele: "Review",

        name: "Name",
        email: "Email",
        phone: "Phone",
        address: "Address",
        message: "Message",
        submit: "Submit",
        sending: "Sending",
        success: "Success",
        error: "Error",
    },
    ru: {
        boyutlar: "Габариты",
        uzunluk: "Длина",
        genislik: "Ширина",
        yukseklik: "Высота",
        agirlik: "Вес",
        enerji_ozellikleri: "Энергетические характеристики",
        yakit_tipi: "ТИП ТОПЛИВА",
        elektrik: "Электричество",
        motorin: "Дизель",
        lpg: "Сжиженный газ (LPG)",
        dogal_gaz: "Природный газ",
        minimum: "Минимум",
        maximum: "Максимум",
        ortalama: "Среднее",
        viewModel: "Просмотр 3D модели",
        capacity: "Производительность",
        electric_component: "Электрические компоненты",
        urun_kapasitesi: "ПРОИЗВОДИТЕЛЬНОСТЬ",
        kapasite: "МОЩНОСТЬ",
        kg_saat: "КГ/ЧАС",
        mm: "мм",
        lt_h: "л/ч",
        kw: "кВт",
        nm3_h: "Нм3/ч",
        kg_h: "кг/ч",
        kg: "кг",
        resistance: "сопротивление",
        fistik: "Арахис",
        kabuklu_fistik: "Арахис в скорлупе",
        tuzlu_fistik: "Соленый арахис",
        antep_fistigi: "Фисташки",
        soslu_fistik: "Фисташка в соусе",
        kaplamali_fistik: "Арахис в оболочке",
        tofy_fistik: "Тофи Арахис",
        amigo_fistik: "Амиго Арахис",
        leblebi: "Жареный нут",
        beyaz_leblebi: "Белый нут",
        sari_leblebi: "Желтый нут",
        citir_leblebi: "Хрустящий нут",
        kaplamali_leblebi: "Нут в оболочке",
        tofy_leblebi: "Тофи нут",
        soslu_leblebi: "Нут в соусе",
        ham_leblebi: "Сырой нут",
        tuzlu_leblebi: "Соленый нут",
        leblebi_sekeri: "Нут в сахаре",
        ay_cekirdegi: "Семена подсолнечника",
        kabak_cekirdegi: "Семена тыквы",
        badem: "Миндаль",
        kabuklu_badem: "Миндаль в скорлупе",
        badem_sekeri: "Миндальные конфеты",
        kahve: "Кофе",
        cips: "Чипсы",
        misir: "Кукуруза",
        kaju: "Кешью",
        findik: "Фундук",
        ceviz: "грецкий орех",
        kabuklu_findik: "Фундук в скорлупе",
        benzerUrunler: "Похожие продукты",
        teklifAl: "Похожие продукты",
        incele: "Обзор",
        name: "Имя",
        email: "Эл. почта",
        phone: "Телефон",
        address: "Адрес",
        message: "Сообщение",
        submit: "представить",
        sending: "Отправка",
        success: "Успех",
        error: "ошибка",
    },
    ar: {
        boyutlar: "الأبعاد",
        uzunluk: "الطول",
        genislik: "العرض",
        yukseklik: "الارتفاع",
        agirlik: "الوزن",
        enerji_ozellikleri: "مواصفات الطاقة",
        yakit_tipi: "نوع الوقود",
        elektrik: "كهرباء",
        motorin: "ديزل",
        lpg: "غاز مسال",
        dogal_gaz: "غاز طبيعي",
        minimum: "الحد الأدنى",
        maximum: "الحد الأقصى",
        ortalama: "متوسط",
        viewModel: "عرض النموذج ثلاثي الأبعاد",
        capacity: "سعة المنتج",
        electric_component: "المكونات الكهربائية",
        urun_kapasitesi: "سعة المنتج",
        kapasite: "السعة",
        kg_saat: "كجم/ساعة",
        mm: "مم",
        lt_h: "لتر/ساعة",
        kw: "كيلو واط",
        nm3_h: "ن.م3/س",
        kg_h: "كجم/س",
        kg: "كجم",
        resistance: "مقاومة",
        fistik: "الفول السوداني",
        kabuklu_fistik: "الفول السوداني المقشر",
        tuzlu_fistik: "فول سوداني مملح",
        antep_fistigi: "فستق حلبي",
        soslu_fistik: "فول سوداني بالصلصة",
        kaplamali_fistik: "فول سوداني مغلف",
        tofy_fistik: "فول سوداني طوفي",
        amigo_fistik: "فول سوداني أميغو",
        leblebi: "حمص",
        beyaz_leblebi: "حمص أبيض",
        sari_leblebi: "حمص أصفر",
        citir_leblebi: "حمص مقرمش",
        kaplamali_leblebi: "حمص مغلف",
        tofy_leblebi: "حمص طوفي",
        soslu_leblebi: "حمص بالصلصة",
        ham_leblebi: "حمص خام",
        tuzlu_leblebi: "حمص مملح",
        leblebi_sekeri: "حلوى الحمص",
        ay_cekirdegi: "بذور عباد الشمس",
        kabak_cekirdegi: "بذور اليقطين",
        badem: "لوز",
        kabuklu_badem: "لوز مقشر",
        badem_sekeri: "حلوى اللوز",
        kahve: "قهوة",
        cips: "رقائق",
        misir: "ذرة",
        kaju: "كاجو",
        findik: "بندق",
        ceviz: "الجوز",
        kabuklu_findik: "بندق مقشر",
        benzerUrunler: "منتجات مماثلة",
        teklifAl: "احصل على عرض",
        incele: "مراجعة",
        name: "الاسم",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        address: "العنوان",
        message: "الرسالة",
        submit: "تقديم",
        sending: "جارٍ الإرسال",
        success: "نجاح",
        error: "خطأ",
    },
    fr: {
        boyutlar: "Dimensions",
        uzunluk: "Longueur",
        genislik: "Largeur",
        yukseklik: "Hauteur",
        agirlik: "Poids",
        enerji_ozellikleri: "Caractéristiques énergétiques",
        yakit_tipi: "TYPE DE CARBURANT",
        elektrik: "Électricité",
        motorin: "Diesel",
        lpg: "GPL",
        dogal_gaz: "Gaz naturel",
        minimum: "Minimum",
        maximum: "Maximum",
        ortalama: "Moyenne",
        viewModel: "Voir le modèle 3D",
        capacity: "Capacités du produit",
        electric_component: "Composants électriques",
        urun_kapasitesi: "CAPACITÉ DU PRODUIT",
        kapasite: "CAPACITÉ",
        kg_saat: "KG/HEURE",
        mm: "mm",
        lt_h: "L/h",
        kw: "kW",
        nm3_h: "Nm3/h",
        kg_h: "kg/h",
        kg: "kg",
        resistance: "Résistance",
        fistik: "Cacahuète",
        kabuklu_fistik: "Cacahuètes en coque",
        tuzlu_fistik: "Cacahuètes salées",
        antep_fistigi: "Pistaches",
        soslu_fistik: "Cacahuètes assaisonnées",
        kaplamali_fistik: "Cacahuètes enrobées",
        tofy_fistik: "Cacahuètes Tofy",
        amigo_fistik: "Cacahuètes Amigo",
        leblebi: "Pois chiches",
        beyaz_leblebi: "Pois chiches blancs",
        sari_leblebi: "Pois chiches jaunes",
        citir_leblebi: "Pois chiches croustillants",
        kaplamali_leblebi: "Pois chiches enrobés",
        tofy_leblebi: "Pois chiches Tofy",
        soslu_leblebi: "Pois chiches assaisonnés",
        ham_leblebi: "Pois chiches crus",
        tuzlu_leblebi: "Pois chiches salés",
        leblebi_sekeri: "Pois chiches sucrés",
        ay_cekirdegi: "Graines de tournesol",
        kabak_cekirdegi: "Graines de courge",
        badem: "Amande",
        kabuklu_badem: "Amandes en coque",
        badem_sekeri: "Dragées aux amandes",
        kahve: "Café",
        cips: "Chips",
        misir: "Maïs",
        kaju: "Noix de cajou",
        findik: "Noisette",
        ceviz: "Noix",
        kabuklu_findik: "Noisettes en coque",
        benzerUrunler: "Produits similaires",
        teklifAl: "Obtenir un devis",
        incele: "Voir",
        name: "Nom",
        email: "Email",
        phone: "Téléphone",
        address: "Adresse",
        message: "Message",
        submit: "soumettre",
        sending: "Envoi en cours",
        success: "Succès",
        error: "Erreur",
    }
}

export default ProductsMessages;