version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: efor-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_DISABLE_ESLINT=1
      - TZ=Europe/Istanbul
    networks: [efornet]
    restart: unless-stopped
    # development için hot reload
    # volumes:
    #   - .:/app
    #   - /app/node_modules

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on: [web]
    networks: [efornet]
    restart: unless-stopped

volumes:
  node_modules:

networks:
  efornet:
    driver: bridge
