const AboutMessages = {
    tr: {
        'AboutMessages.title': "Kuruyemişlerin rotasını teknolojiyle çiziyoruz",
        title_top: "Kuruyemişlerin rotasını",
        title_alt: "teknolojiyle çiziyoruz",
        short_desc: "2015 yılından bu yana Kuruyemiş Kavurma Makinaları imalatına başlayarak faaliyetlerini sürdüren Efor Makina, üretim de daima en iyiyi hedefleyen bir firmadır.",
        desc: "2015 yılından bu yana Kuruyemiş Kavurma Makinaları imalatına başlayarak faaliyetlerini sürdüren Efor Makina, üretim de daima en iyiyi hedefleyen bir firmadır. Kaliteli üretimi ilke haline getiren şirketimiz; Sağlık, insan ve üretim mottosuyla yola çıkarak uluslararası standartlarda üretimine devam etmektedir. Sektöründe tartışılmaz bir önderliğe sahip olan Efor Kuruyemiş Makinaları İmalat San. ve Tic. LTD. ŞTİ, profesyonel ekibi ve çözüm odaklı yaklaşımlarıyla müşteri memnuniyetini birinci konumda tutmaktadır. Çağdaş makina parkuruyla kolaylığı, teknolojiyle üretim verimliliğini sağlayan firmamız, nitelikli Kuruyemiş Makinaları ile her zaman hizmetinizdedir...",
        prod_range: "Ürün Çeşidi",
        customer_satis: "Müşteri Memnuniyeti",
        export: "Ülkeye İhracat",
    },
    en: {
        'AboutMessages.title': "Draw the route of nuts with technology",
        title_top: "The route of nuts",
        title_alt: "draw with technology",
        short_desc: "Efor Machine, which has been continuing its activities by starting to manufacture Nut Roasting Machines since 2015, is a company that always targets the best in production. ",
        desc: "Efor Machine, which has been continuing its activities by starting to manufacture Nut Roasting Machines since 2015, is a company that always targets the best in production. Our company, which has made quality production a principle, continues its production at international standards by starting with the motto of health, human and production. Having an indisputable leadership in the sector, Efor Kuruyemiş Makinaları Imalat San. and tic. ltd. ŞTI keeps customer satisfaction in the first position with its professional team and solution-oriented approaches. Our company, which provides ease with its modern machinery park, production efficiency with technology, is always at your service with qualified Nuts Machines... ",
        prod_range: "Product Range",
        customer_satis: "Customers Satisfaction",
        export: "Exported Countries",
    },
    ru: {
        'AboutMessages.title': "Мы рисуем маршрут из орехов с помощью технологий",
        title_top: "Маршрут орехов ",
        title_alt: "мы рисуем с помощью техники",
        short_desc: "Эфор Машина, которая продолжает свою деятельность, начав производство машин для обжаривания орехов с 2015 года, является компанией, которая всегда стремится к лучшему в производстве.",
        desc: "Эфор Машина, которая продолжает свою деятельность, начав производство машин для обжаривания орехов с 2015 года, является компанией, которая всегда стремится к лучшему в производстве. Наша компания, принципом которой является качественное производство; Начав с девиза здоровья, людей и производства, он продолжает производство в соответствии с международными стандартами. Имея бесспорное лидерство в своем секторе, Efor Kuruyemiş Makinaları İmalat San.Ve TİC. LTD, с его профессиональной командой и подходами, ориентированными на решение, удерживает удовлетворенность клиентов на первом месте. Наша компания, которая обеспечивает удобство с помощью современного машинного парка и эффективность производства с помощью технологий, всегда к вашим услугам со своим квалифицированным оборудованием для обжарки орехов... ",
        prod_range: "Ассортимент продукции",
        customer_satis: "Удовлетворенность клиентов",
        export: "Страны-экспортеры",
    },
    ar: {
        'AboutMessages.title': "نرسم طريق المكسرات بالتكنولوجيا",
        title_top: "مسار المكسرات ",
        title_alt: "نرسم بالتكنولوجيا",
        short_desc: "شركة إيفور لآلات التحميص التي تواصل أنشطتها من خلال بدء إنتاج ماكينات تحميص المكسرات منذ عام 2015 ، هي شركة تهدف دائمًا إلى الأفضل في الإنتاج. شركتنا ، التي تجعل جودة الإنتاج مبدأ ؛",
        desc: "شركة إيفور لآلات التحميص التي تواصل أنشطتها من خلال بدء إنتاج ماكينات تحميص المكسرات منذ عام 2015 ، هي شركة تهدف دائمًا إلى الأفضل في الإنتاج. شركتنا ، التي تجعل جودة الإنتاج مبدأ ؛ انطلاقًا من شعار الصحة والإنسان والإنتاج ، تواصل إنتاجها وفقًا للمعايير الدولية. تحافظ ايفور ، التي تتمتع بقيادة لا جدال فيها في قطاعها ، على رضا العملاء في المقام الأول من خلال فريقها المحترف ونُهُجها الموجهة نحو الحلول. شركتنا ، التي توفر الراحة من خلال مجموعة الماكينات الحديثة وكفاءة الإنتاج مع التكنولوجيا ، هي دائمًا في خدمتك من خلال ماكينات المكسرات الممتازة ... ",
        prod_range: "نوع المنتج",
        customer_satis: "إسعاد المتعاملين",
        export: "تصدير إلى الدولة",
    },
    fr: {
        'AboutMessages.title': "Tracez l'itinéraire des noix à l'aide de la technologie",
        title_top: "La route des noix",
        title_alt: "dessiner avec la technologie",
        short_desc: "2Efor Machine, qui poursuit ses activités depuis 2015 en se lançant dans la fabrication de machines à torréfier les noix, est une entreprise qui vise toujours l'excellence dans la production.",
        desc: "Depuis 2015, Efor Makina poursuit ses activités en se consacrant à la fabrication de machines de torréfaction de fruits secs. Notre entreprise, qui a fait de la qualité de production son principe fondamental, poursuit sa production selon les normes internationales en se basant sur les mots d'ordre « santé, homme et production ». Leader incontesté dans son secteur, Efor Kuruyemiş Makinaları İmalat San. ve Tic. LTD. ŞTİ place la satisfaction de ses clients au premier plan grâce à son équipe professionnelle et à son approche axée sur les solutions. Notre entreprise, qui allie facilité d'utilisation et efficacité de production grâce à son parc de machines modernes, est toujours à votre service avec ses machines de torréfaction de fruits secs de qualité...",
        prod_range: "Gamme de produits",
        customer_satis: "Satisfaction des clients",
        export: "Pays exportateurs",
    },
}

export default AboutMessages;