const ContactFormMessages = {
    tr: {
        name: "Ad",
        email: "E-Posta",
        phone: "Telefon",
        address: "Adres",
        message: "Mesaj",
        message_desc: "Mesajınızı Buraya Yazın...",
        form_desc: "Aşağıdaki formu doldurarak bize mesajınızı iletebilirsiniz. En kısa sürede size geri dönüş yapacağız.",
        form: "İletişim Formu",
        send: "Gönder",
        sending: "Gönderiliyor...",
    },
    en: {
        name: "Name",
        email: "Email",
        phone: "Phone",
        address: "Address",
        message: "Message",
        message_desc: "Write your message here...",
        form: "Contact Form",
        form_desc: "You can send us your message by filling out the form below. We will get back to you as soon as possible.",
        send: "Send",
        sending: "Sending...",
    },
    ru: {
        name: "Имя",
        email: "Эл. почта",
        phone: "Телефон",
        address: "Адрес",
        message: "Сообщение",
        message_desc: "Напишите здесь свое сообщение...",
        form: "Форма обратной связи",
        form_desc: "Вы можете отправить нам сообщение, заполнив форму ниже. Мы свяжемся с вами в ближайшее время.",
        send: "Отправить",
        sending: "Отправка...",
    },
    ar: {
        name: "الاسم",
        email: "البريد الإلكتروني",
        phone: "رقم الهاتف",
        address: "العنوان",
        message: "الرسالة",
        message_desc: "اكتب رسالتك هنا...",
        form: "نموذج الاتصال",
        form_desc: "يمكنك إرسال رسالتك إلينا من خلال تعبئة النموذج أدناه. سنقوم بالرد عليك في أقرب وقت ممكن.",
        send: "إرسال",
        sending: "إرسال...",
    },
    fr: {
        name: "Nom",
        email: "Email",
        phone: "Téléphone",
        address: "Adresse",
        message: "Message",
        message_desc: "Écrivez votre message ici...",
        form: "Formulaire de contact",
        form_desc: "Vous pouvez nous envoyer un message en remplissant le formulaire ci-dessous. Nous vous répondrons dans les plus brefs délais.",
        send: "Envoyer",
        sending: "Envoi...",
    }
}

export default ContactFormMessages;