const LinesMessages = {
    tr: {
        top_text: "Tam Otomatik",
        alt_text: "Kuruyemiş Kavurma Hatları",
        title_1: "Kuruyemiş Kavurma Hattı",
        desc_1: "Efor makine , Gıda üretim tesislerinin ihtiyaçlarına uygun olarak tam otomatik kuruyemiş kavurma hatları üretmektedir. Daha az iş gücüyle önemli derecede maliyet ve zaman tasarrufu sağlayarak yüksek kapasitelerde üretim yapmanıza olanak sağlamaktadır.",
        title_2: "Kahve Kavurma Hattı",
        desc_2: "Efor makine , Gıda üretim tesislerinin ihtiyaçlarına uygun olarak tam otomatik kahve kavurma hatları üretmektedir. Daha az iş gücüyle önemli derecede maliyet ve zaman tasarrufu sağlayarak yüksek kapasitelerde üretim yapmanıza olanak sağlamaktadır.",
        title_3: "Kuruyemiş Fritöz Hattı",
        desc_3: "Efor makine , Gıda üretim tesislerinin ihtiyaçlarına uygun olarak tam otomatik Kuruyemiş fritöz hatları üretmektedir. Daha az iş gücüyle önemli derecede maliyet ve zaman tasarrufu sağlayarak yüksek kapasitelerde üretim yapmanıza olanak sağlamaktadır.",
        button_text: "Devamını Oku",
    },
    en: {
        top_text: "Full Automatic",
        alt_text: "Nuts Roasting Lines",
        title_1: "Nuts Roasting Line",
        desc_1: "Efor Makine produces fully automatic nut roasting lines in accordance with the needs of food production facilities. It enables you to produce at high capacities by providing significant cost and time savings with less labor force. Thanks to the advanced automation system, all processes can be managed through the touch panel. You can manage your production process with maximum efficiency by providing integration with central control systems, together with other equipment in the enterprise.",
        title_2: "Coffee Roasting Line",
        desc_2: "Efor Makine produces fully automatic coffee roasting lines in accordance with the needs of food production facilities. It enables you to produce at high capacities by providing significant cost and time savings with less labor force. Thanks to the advanced automation system, all processes can be managed through the touch panel. You can manage your production process with maximum efficiency by providing integration with central control systems, together with other equipment in the enterprise.",
        title_3: "Nuts Fryer Line",
        desc_3: "Efor Makine produces fully automatic Nuts fryer lines in accordance with the needs of food production facilities. It enables you to produce at high capacities by providing significant cost and time savings with less labor force. Thanks to the advanced automation system, all processes can be managed through the touch panel. You can manage your production process with maximum efficiency by providing integration with central control systems, together with other equipment in the enterprise.",
        button_text: "Read More",
    },
    ru: {
        top_text: "Полностью автоматический",
        alt_text: "линии обжарки орехов",
        title_1: "Линия для обжарки орехов",
        desc_1: "Эфор производит полностью автоматические линии для обжаривания орехов в соответствии с потребностями пищевых производств. Это позволяет вам производить продукцию с высокой производительностью, обеспечивая значительную экономию средств и времени при меньшем количестве рабочей силы. Благодаря развитой системе автоматизации, всеми процессами можно управлять через сенсорную панель.Вы можете управлять своим производственным процессом с максимальной эффективностью, обеспечив интеграцию с центральными системами управления, совместно с другим оборудованием на предприятии.",
        title_2: "Линия для обжарки кофе",
        desc_2: "Эфор производит полностью автоматические линии для обжарки кофе в соответствии с потребностями пищевых производств. Это позволяет вам производить продукцию с высокой производительностью, обеспечивая значительную экономию средств и времени при меньшем количестве рабочей силы. Благодаря развитой системе автоматизации, всеми процессами можно управлять через сенсорную панель.Вы можете управлять своим производственным процессом с максимальной эффективностью, обеспечив интеграцию с центральными системами управления, совместно с другим оборудованием на предприятии.",
        title_3: "Линия из фритюрницы для обжаривания орехов",
        desc_3: "Efor Makine производит полностью автоматические линии для обжаривания орехов в соответствии с потребностями предприятий пищевой промышленности. Это позволяет вам производить продукцию с высокой производительностью, обеспечивая значительную экономию средств и времени при меньшем количестве рабочей силы. Благодаря развитой системе автоматизации, всеми процессами можно управлять через сенсорную панель.Вы можете управлять своим производственным процессом с максимальной эффективностью, обеспечив интеграцию с центральными системами управления, совместно с другим оборудованием на предприятии.",
        button_text: "Читать далее",
    },
    ar: {
        top_text: "التلقائي بالكامل",
        alt_text: " خطوط تحميص المكسرات ",
        title_1: "خط تحميص المكسرات",
        desc_1: "تنتج Efor Makine خطوط تحميص أوتوماتيكية بالكامل وفقًا لاحتياجات مرافق إنتاج الأغذية. إنها تمكنك من الإنتاج بقدرات عالية من خلال توفير التكلفة والوقت بشكل كبير مع قوة عاملة أقل. بفضل نظام التشغيل الآلي المتقدم ، يمكن إدارة جميع العمليات من خلال لوحة اللمس.يمكنك إدارة عملية الإنتاج الخاصة بك بأقصى قدر من الكفاءة من خلال توفير التكامل مع أنظمة التحكم المركزية ، جنبًا إلى جنب مع المعدات الأخرى في المؤسسة.",
        title_2: "خط تحميص البن",
        desc_2: "تنتج شركة Efor Makine خطوط تحميص قهوة أوتوماتيكية بالكامل وفقًا لاحتياجات مرافق إنتاج الأغذية. إنها تمكنك من الإنتاج بقدرات عالية من خلال توفير التكلفة والوقت بشكل كبير مع قوة عاملة أقل. بفضل نظام التشغيل الآلي المتقدم ، يمكن إدارة جميع العمليات من خلال لوحة اللمس.يمكنك إدارة عملية الإنتاج الخاصة بك بأقصى قدر من الكفاءة من خلال توفير التكامل مع أنظمة التحكم المركزية ، جنبًا إلى جنب مع المعدات الأخرى في المؤسسة.",
        title_3: "خط قلاية المكسرات",
        desc_3: "تنتج شركة Efor Makine خطوط قلاية مكسرات أوتوماتيكية بالكامل وفقًا لاحتياجات مرافق إنتاج الأغذية. إنها تمكنك من الإنتاج بقدرات عالية من خلال توفير التكلفة والوقت بشكل كبير مع قوة عاملة أقل. بفضل نظام التشغيل الآلي المتقدم ، يمكن إدارة جميع العمليات من خلال لوحة اللمس.يمكنك إدارة عملية الإنتاج الخاصة بك بأقصى قدر من الكفاءة من خلال توفير التكامل مع أنظمة التحكم المركزية ، جنبًا إلى جنب مع المعدات الأخرى في المؤسسة.",
        button_text: "اقرأ المزيد",
    },
    fr: {
        top_text: "Entièrement automatique",
        alt_text: "Lignes de torréfaction des noix",
        title_1: "Ligne de torréfaction des noix",
        desc_1: "Efor makine , Gıda üretim tesislerinin ihtiyaçlarına uygun olarak tam otomatik kuruyemiş kavurma hatları üretmektedir. Daha az iş gücüyle önemli derecede maliyet ve zaman tasarrufu sağlayarak yüksek kapasitelerde üretim yapmanıza olanak sağlamaktadır.",
        title_2: "Kahve Kavurma Hattı",
        desc_2: "Efor makine , Gıda üretim tesislerinin ihtiyaçlarına uygun olarak tam otomatik kahve kavurma hatları üretmektedir. Daha az iş gücüyle önemli derecede maliyet ve zaman tasarrufu sağlayarak yüksek kapasitelerde üretim yapmanıza olanak sağlamaktadır.",
        title_3: "Kuruyemiş Fritöz Hattı",
        desc_3: "Efor makine , Gıda üretim tesislerinin ihtiyaçlarına uygun olarak tam otomatik Kuruyemiş fritöz hatları üretmektedir. Daha az iş gücüyle önemli derecede maliyet ve zaman tasarrufu sağlayarak yüksek kapasitelerde üretim yapmanıza olanak sağlamaktadır.",
        button_text: "Lire la suite",
    },
}

export default LinesMessages;